# 模型架构参数
in_channels: 64   # 修改为实际的输入特征维度
hidden_channels: 256  # 增加模型容量
num_layers: 4      # 增加层数以捕获更复杂的模式
dropout: 0.5       # 适当降低dropout

# 训练参数
learning_rate: 0.001  # 降低学习率
weight_decay: 0.001   # 增加正则化
epochs: 200         # 增加训练轮数
early_stopping: 30    # 增加早停耐心值

# 损失函数参数
edge_loss_weight: 0.2  # 增加结构正则化权重
aux_loss_weight: 0.3    # Reddit数据集上降低辅助损失权重
guidance_alpha: 0.3    # 增加正样本权重以平衡类别
guidance_beta: 0.6     # 偏重上下文级损失，因为Reddit社区结构更明显

# 数据集参数
dataset_name: 'reddit'
data_path: 'reddit.pt'

# 负样本采样参数
num_neg_samples: 15  # 增加负样本数量
k_hop: 2  # 减少跳数以关注更局部的结构
similarity_threshold: 0.5  # 提高相似度阈值
batch_size: 1000  # 添加批处理大小参数 